   name: unit_tests

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: unit_tests
        run: make unit_tests
      - name: clean
        run: make clean
